# Generated by Django 5.0.6 on 2024-07-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultofvoting',
            options={'ordering': ('-voting_date',)},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('-created_at',)},
        ),
    ]
