# Generated by Django 5.0.6 on 2024-07-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cafelunchmenu',
            unique_together={('weekday', 'cafe')},
        ),
    ]
